rl_model: "MaskableRecurrentPPO"
seed: 1
hidden_layers: [128, 128]
activation_fn: "tanh"
learning_rate: 0.000275
n_steps: 512
batch_size: 256
ent_coef: 0.0035
gamma: 0.94
total_steps: 1000000
clip_range: 0.38
clip_range_vf: 0.27
lstm_hidden_size: 64
n_lstm_layers: 3