rl_model: "MaskableRecurrentPPO"
learning_scheduler: "constant"
seed: 0
hidden_layers: 64
n_hidden_layers: 2
activation_fn: "ReLU"
learning_rate: 0.00041375
n_steps: 64
batch_size: 512
ent_coef: 0.0024367
gamma: 0.95597
total_steps: 600
clip_range: 0.35116
clip_range_vf: 0.21794
lstm_hidden_size: 64
n_lstm_layers: 1