rl_model: "MaskablePPO"
learning_scheduler: "constant"
seed: 2
hidden_layers: 64
n_hidden_layers: 3
activation_fn: "ReLU"
learning_rate: 0.0037115
n_steps: 290
batch_size: 145
ent_coef: 0.0050344
gamma: 1
total_steps: 1450
clip_range: 0.11733
clip_range_vf: 0.28446