rl_model: "MaskableRecurrentPPO"
learning_scheduler: "linear"
seed: 1
hidden_layers: 128
n_hidden_layers: 2
activation_fn: "ReLU"
learning_rate: 0.004
n_steps: 512
batch_size: 128
ent_coef: 0.005
gamma: 0.99
total_steps: 1000000
clip_range: 0.26
clip_range_vf: 0.20
lstm_hidden_size: 256
n_lstm_layers: 2